const CFG=window.WRC_CONFIG||{}; const API=CFG.apiBase||'';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={task:'baseline',raw:[],mapping:[],normalized:[],validation:null,runId:'',snapshotId:'',resolvedRequest:null,queryTrace:[],baseline:null,scenario:null,role:'risk',workflow:0};
const wfNames=['识别用户意图','确定所需字段','AI抽取/字段映射','数据校验','人工确认企业数据','缺失数据来源路由','判断计算模式','冻结数据快照/版本','调用 Baseline / Scenario','程序识别高风险节点与变化','AI角色化解释与建议','人工复核/导出/运行轨迹'];
function renderWorkflow(){const el=$('#workflow');el.innerHTML=wfNames.map((n,i)=>`<div class="wf-step ${i<state.workflow?'done':i===state.workflow?'active':''}"><i>${i+1}</i><span>${n}</span></div>`).join('')}
function advance(n){state.workflow=Math.max(state.workflow,n);renderWorkflow()}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
async function api(path,opts={}){const r=await fetch(API+path,opts);if(!r.ok){let m='请求失败';try{m=(await r.json()).detail||m}catch(e){}throw new Error(m)}return r.json()}
function esc(v){return String(v??'').replace(/[&<>"']/g,s=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[s]))}
function fmt(v,n=4){const x=Number(v);return Number.isFinite(x)?x.toFixed(n):(v??'—')}
function pct(v){const x=Number(v);return Number.isFinite(x)?(x*100).toFixed(1)+'%':'—'}
function markdownish(s=''){return esc(s).replace(/^### (.*)$/gm,'<h3>$1</h3>').replace(/\*\*(.*?)\*\*/g,'<b>$1</b>').replace(/^- (.*)$/gm,'<p>• $1</p>').replace(/\n/g,'<br>')}
function table(el,rows,cols=null){const t=typeof el==='string'?$(el):el;if(!rows||!rows.length){t.innerHTML='<tbody><tr><td>暂无数据</td></tr></tbody>';return}cols=cols||Object.keys(rows[0]);t.innerHTML='<thead><tr>'+cols.map(c=>`<th>${esc(c)}</th>`).join('')+'</tr></thead><tbody>'+rows.map(r=>'<tr>'+cols.map(c=>`<td>${typeof r[c]==='object'?esc(JSON.stringify(r[c])):esc(r[c]??'')}</td>`).join('')+'</tr>').join('')+'</tbody>'}
function showPage(name){$$('.page').forEach(x=>x.classList.remove('active'));$('#page-'+name).classList.add('active');$$('.nav').forEach(x=>x.classList.toggle('active',x.dataset.page===name));const titles={overview:'AI Agent 总览',input:'输入与数据治理',baseline:'Baseline 确定性计算',scenario:'Scenario 压力测试',assistant:'AI 决策助手',evidence:'证据与追溯',qa:'QA / 黄金样例',export:'导出与日志'};$('#pageTitle').textContent=titles[name]||'';if(name==='export')loadLogs();window.scrollTo({top:0,behavior:'smooth'})}

$('#sisterLink').href=CFG.sisterSite||'#';renderWorkflow();$$('.nav').forEach(b=>b.onclick=()=>showPage(b.dataset.page));$$('.jump').forEach(b=>b.onclick=()=>showPage(b.dataset.target));
(async()=>{try{const r=await api('/api/health');$('#health').textContent='● 后端在线 · '+r.version;$('#enginePill').textContent=r.baseline_engine; }catch(e){$('#health').textContent='● 后端未连接'}})();

function renderMapping(){const cols=state.raw.length?Object.keys(state.raw[0]):[];$('#mappingTable').innerHTML='<thead><tr><th>系统字段</th><th>用户字段</th><th>关键性</th></tr></thead><tbody>'+state.mapping.map((m,i)=>`<tr><td><b>${esc(m.system_field)}</b></td><td><select class="mapSel" data-i="${i}"><option value="">— 未映射 —</option>${cols.map(c=>`<option value="${esc(c)}" ${c===m.source_column?'selected':''}>${esc(c)}</option>`).join('')}</select></td><td>${m.required?'关键':'可选'}</td></tr>`).join('')+'</tbody>';$$('.mapSel').forEach(x=>x.onchange=e=>state.mapping[+e.target.dataset.i].source_column=e.target.value)}
function renderValidation(){const v=state.validation||{};const cards=[['状态',v.status||'—']];Object.entries(v.coverage||{}).forEach(([k,x])=>cards.push([k+' 已知覆盖',pct(x)]));cards.push(['Warnings',(v.warnings||[]).length],['Data gaps',(v.data_gaps||[]).length]);$('#validationCards').innerHTML=cards.map(([k,v])=>`<div class="metric"><span>${esc(k)}</span><strong>${esc(v)}</strong></div>`).join('')}
async function loadDemo(material='甘蔗'){const r=await api('/api/demo/'+encodeURIComponent(material));state.raw=r.records;state.mapping=r.mapping;table('#rawTable',state.raw);renderMapping();$('#rawPanel').hidden=false;$('#mappingPanel').hidden=false;$('#inputMsg').className='notice warn';$('#inputMsg').textContent=r.warning;advance(2);showPage('input');toast('已载入示范数据')}
$('#demoQuick').onclick=()=>loadDemo('甘蔗');$('#demoBtn').onclick=()=>loadDemo($('#demoMaterial').value);$('#taskSelect').onchange=e=>{state.task=e.target.value;advance(1)};
$('#uploadBtn').onclick=async()=>{state.task=$('#taskSelect').value;advance(1);const f=$('#fileInput').files[0];if(!f){toast('请先选择文件');return}const fd=new FormData();fd.append('file',f);$('#inputMsg').textContent='正在读取…';try{const r=await fetch(API+'/api/upload',{method:'POST',body:fd}).then(async x=>{if(!x.ok)throw new Error((await x.json()).detail||'上传失败');return x.json()});state.raw=r.records;state.mapping=r.mapping;table('#rawTable',state.raw);renderMapping();$('#rawPanel').hidden=false;$('#mappingPanel').hidden=false;$('#inputMsg').className='notice good';$('#inputMsg').textContent=r.message;advance(3);toast('候选字段已生成')}catch(e){$('#inputMsg').className='notice bad';$('#inputMsg').textContent=e.message}};
$('#confirmBtn').onclick=async()=>{if(!$('#humanConfirm').checked){toast('请先人工确认');return}try{const r=await api('/api/confirm',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({records:state.raw,mapping:state.mapping,weight_mode:$('#weightMode').value,human_confirmed:true,task:state.task})});state.normalized=r.records||[];state.validation=r.validation||{};state.runId=r.run_id||'';state.snapshotId=r.snapshot_id||'';renderValidation();$('#snapshotPill').textContent=state.snapshotId;$('#resolvedPanel').hidden=false;advance(5);toast('Snapshot 已冻结')}catch(e){toast(e.message)}};
$('#resolveBtn').onclick=async()=>{if(!state.normalized.length){toast('请先确认数据');return}try{const r=await api('/api/resolve-input',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({records:state.normalized,run_id:state.runId})});state.resolvedRequest=r.resolved_request;state.queryTrace=r.query_trace||[];$('#resolvedJson').textContent=JSON.stringify(state.resolvedRequest,null,2);$('#queryTrace').textContent=JSON.stringify(state.queryTrace,null,2);advance(8);refreshEvidenceSelectors();toast(r.status==='success'?'D Request 已生成':'D Request 存在 Schema 问题')}catch(e){toast(e.message)}};
$$('.tab').forEach(b=>b.onclick=()=>{$$('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#resolvedJson').hidden=b.dataset.json!=='resolvedJson';$('#queryTrace').hidden=b.dataset.json!=='queryTrace'});

function renderBaseline(b){const m=(b.materials||[])[0];$('#baselineMeta').innerHTML=`Run ID: <b>${esc(b.run_id)}</b> · Input Hash: <b>${esc(b.input_hash)}</b> · ${esc(b.engine_version)} · ${esc(b.formula_version)} · ${esc(b.data_version)}`;if(!m){$('#baselineMetrics').innerHTML='';$('#baselineQuality').innerHTML=markdownish((b.brief||''));return}const metrics=[['PRWI',fmt(m.PRWI)],['采购覆盖',pct(m.procurement_coverage)],['可评分覆盖',pct(m.scored_coverage)],['Unknown',pct(m.unknown_share)],['模式',m.calculation_mode||b.calculation_mode],['证据可信度',m.overall_confidence||'Unknown'],['Procurement HHI',fmt(m.procurement_HHI)],['Risk HHI',fmt(m.risk_HHI)]];$('#baselineMetrics').innerHTML=metrics.map(([k,v])=>`<div class="metric"><span>${esc(k)}</span><strong>${esc(v)}</strong></div>`).join('');$('#baselineBrief').innerHTML=markdownish(b.brief||'');const q=[`Status: ${b.status}`,`Input schema: ${b.schema_validation?.input_valid?'PASS':'FAIL'}`,`Output schema: ${b.schema_validation?.output_valid?'PASS':'FAIL'}`,`Missing: ${(b.missing_fields||[]).length}`,`Proxy: ${(b.proxy_fields||[]).length}`,`Warnings: ${(b.warnings||[]).length}`].join('\n');$('#baselineQuality').innerHTML=markdownish(q);table('#baselineTable',m.nodes||[],['rank','node_id','node_name','W','R','C','contribution_share','node_status']);refreshVersionChain()}
$('#baselineBtn').onclick=async()=>{if(!state.resolvedRequest){toast('请先生成 D Request');showPage('input');return}try{const r=await api('/api/baseline',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({request:state.resolvedRequest})});state.baseline=r;$('#baselineEmpty').hidden=true;$('#baselineResult').hidden=false;renderBaseline(r);advance(10);toast(`Baseline: ${r.status}`)}catch(e){toast(e.message)}};

$('#scenarioBtn').onclick=async()=>{if(!state.baseline){toast('请先运行 Baseline');return}const body={baseline:state.baseline,scenario_type:$('#scenarioType').value,material:$('#scenarioMaterial').value,year:+$('#futureYear').value,path:$('#futurePath').value,failure_fraction:+$('#failureFraction').value,inventory:+$('#inventory').value};try{const r=await api('/api/scenario',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});state.scenario=r;if(!r.data){toast((r.warnings||r.data_gaps||['Scenario未运行']).join('；'));return}$('#scenarioEmpty').hidden=true;$('#scenarioResult').hidden=false;$('#scenarioMeta').innerHTML=`${esc(r.scenario_type)} · Baseline Run: <b>${esc(r.baseline_run_id)}</b> · Input Hash: <b>${esc(r.baseline_input_hash)}</b> · ${esc(r.scenario_version)}`;$('#scenarioBrief').innerHTML=markdownish(r.brief||'');let delta='';if(r.scenario_type==='NodeFailure'){const d=r.data;delta=`Gross Loss: ${pct(d.gross_loss)}\nInventory Used: ${pct(d.inventory_used)}\nReplacement: ${pct(d.replacement_allocated)}\nUnmet Demand: ${pct(d.unmet_demand)}\nConditional PRWI: ${fmt(d.conditional_PRWI)}`;table('#scenarioTable',d.node_table||[])}else{const s=(r.data.summary||[])[0]||{};delta=`Baseline: ${fmt(s.PRWI_baseline)}\nScenario: ${fmt(s.PRWI_scenario??s.PRWI_future)}\nΔPRWI: ${fmt(s.PRWI_delta)}`;table('#scenarioTable',r.data.node_table||[])}$('#scenarioDelta').innerHTML=markdownish(delta);advance(10);refreshVersionChain();toast(`Scenario: ${r.status}`)}catch(e){toast(e.message)}};

function addMsg(role,text,trace=''){const box=$('#chatMessages'),n=document.createElement('div');n.className='msg '+(role==='assistant'?'ai':'user');n.innerHTML=`<div class="avatar">${role==='assistant'?'AI':'你'}</div><div class="bubble">${trace?`<div class="trace">${esc(trace)}</div>`:''}${role==='assistant'?markdownish(text):esc(text)}</div>`;box.appendChild(n);box.scrollTop=box.scrollHeight}
async function sendChat(text){text=(text||'').trim();if(!text)return;addMsg('user',text);$('#chatInput').value='';try{const r=await api('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:text,role:state.role,validation:state.validation,resolved_request:state.resolvedRequest,baseline:state.baseline,scenario:state.scenario})});const trace=`Intent: ${r.intent} · Router: ${r.router_source} · Tools: ${(r.tool_calls||[]).join(' → ')||'等待前置条件'}`;addMsg('assistant',r.answer,trace);$('#agentTrace').textContent=JSON.stringify({intent:r.intent,scenario_type:r.scenario_type,confidence:r.confidence,router_source:r.router_source,tool_calls:r.tool_calls},null,2);advance(11)}catch(e){addMsg('assistant','调用失败：'+e.message)}}
$('#chatBtn').onclick=()=>sendChat($('#chatInput').value);$('#chatInput').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();sendChat(e.target.value)}});$$('.suggest').forEach(b=>b.onclick=()=>sendChat(b.textContent));$$('.role').forEach(b=>b.onclick=()=>{$$('.role').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.role=b.dataset.role;toast('已切换角色：'+b.textContent)});

function refreshEvidenceSelectors(){const matSel=$('#evidenceMaterial'),nodeSel=$('#evidenceNode');const mats=state.resolvedRequest?.materials||[];matSel.innerHTML=mats.map(m=>`<option>${esc(m.material)}</option>`).join('');const fill=()=>{const m=mats.find(x=>x.material===matSel.value)||mats[0];nodeSel.innerHTML=(m?.nodes||[]).map(n=>`<option value="${esc(n.node_id)}">${esc(n.node_name||n.node_id)}</option>`).join('')};matSel.onchange=fill;fill()}
$('#evidenceBtn').onclick=()=>{const mats=state.resolvedRequest?.materials||[];const m=mats.find(x=>x.material===$('#evidenceMaterial').value);const n=(m?.nodes||[]).find(x=>x.node_id===$('#evidenceNode').value);if(!n){toast('尚无 Resolved Input');return}const fields=['W','WS','SV','DR','BWD','DYS','CTS','OA'];$('#evidenceCards').innerHTML=fields.map(f=>{const meta=n.field_meta?.[f]||m.field_meta?.[f]||{};let val=n[f];if(val==null) val=m.material_params?.[f];return `<div class="evidence"><span>${f}</span><b>${esc(val??'Missing')}</b><small>${esc(meta.source_ref||'Unknown')}</small><span class="tag">${esc(meta.data_status||'Unknown')} · ${esc(meta.confidence||'Unknown')}</span></div>`}).join('')};
function refreshVersionChain(){const b=state.baseline,s=state.scenario,r=state.resolvedRequest;const rows=[];if(r)rows.push(['Data',r.data_version],['Run ID',r.run_id]);if(b)rows.push(['Input Hash',b.input_hash],['Engine',b.engine_version],['Formula',b.formula_version],['Parameters',b.parameter_version]);if(s)rows.push(['Scenario',s.scenario_version],['Scenario Baseline Hash',s.baseline_input_hash]);$('#versionChain').innerHTML=rows.length?rows.map(([k,v])=>`<div class="version-item"><b>${esc(k)}</b><br>${esc(v??'—')}</div>`).join(''):'尚无运行结果。';$('#runIdentity').innerHTML=markdownish(rows.map(([k,v])=>`- ${k}: **${v??'—'}**`).join('\n'))}

$('#qaBtn').onclick=async()=>{try{const r=await api('/api/qa');const rows=(r.cases||[]).map(x=>({case:x.case,expected_status:x.expected_status,actual_status:x.actual_status,expected_mode:x.expected_mode,actual_mode:x.actual_mode,input_schema:x.checks.input_schema?'✓':'✕',output_schema:x.checks.output_schema?'✓':'✕',status_match:x.checks.status_match?'✓':'✕',mode_match:x.checks.mode_match?'✓':'✕',PRWI_match:x.checks.prwi_match?'✓':'✕',overall:x.pass?'PASS':'CHECK'}));table('#qaTable',rows);$('#qaNote').textContent=r.note;toast('QA 已运行')}catch(e){toast(e.message)}};

$('#exportBtn').onclick=async()=>{if(!state.baseline){toast('请先运行 Baseline');return}try{const r=await fetch(API+'/api/export',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({baseline:state.baseline,scenario:state.scenario,validation:state.validation,resolved_request:state.resolvedRequest,snapshot_id:state.snapshotId,role:state.role})});if(!r.ok)throw new Error((await r.json()).detail||'导出失败');const blob=await r.blob(),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='Water_Risk_Copilot_风险管理简报.docx';a.click();URL.revokeObjectURL(url);$('#exportMsg').className='notice good';$('#exportMsg').textContent='Word 简报已生成。';advance(12);loadLogs()}catch(e){$('#exportMsg').className='notice bad';$('#exportMsg').textContent=e.message}};
async function loadLogs(){try{const r=await api('/api/logs');const rows=(r.logs||[]).slice().reverse().map(x=>({timestamp:x.timestamp,run_id:x.run_id,event:x.event,status:x.status||'',input_hash:x.input_hash||x.baseline_input_hash||'',version:x.engine_version||x.scenario_version||'',intent:x.intent||''}));table('#logsTable',rows,['timestamp','run_id','event','status','input_hash','version','intent']);refreshVersionChain()}catch(e){}}
$('#refreshLogs').onclick=loadLogs;
